---
# =============================================================================
# MaaS RAG Example - One-Step Deployment
# =============================================================================
# This playbook handles everything:
# 1. Validates credentials
# 2. Installs collection
# 3. Deploys the workload
# 4. Tests the deployment
#
# Usage:
#   ansible-playbook deploy.yml -e litellm_api_base_url=https://... -e litellm_virtual_key=sk-...
# =============================================================================

- name: Deploy MaaS RAG Example - Complete
  hosts: localhost
  gather_facts: false

  tasks:
    # -------------------------------------------------------------------------
    # Step 1: Validate OpenShift Connection
    # -------------------------------------------------------------------------
    - name: Check OpenShift connection
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: default
      register: r_oc_check
      failed_when: false

    - name: Fail if not logged into OpenShift
      ansible.builtin.fail:
        msg: |
          Not logged into OpenShift!
          Please run: oc login https://YOUR_CLUSTER_URL:6443 --token=YOUR_TOKEN
      when: r_oc_check.failed | default(false)

    - name: Display OpenShift connection
      ansible.builtin.debug:
        msg: "✓ Connected to OpenShift cluster"

    # -------------------------------------------------------------------------
    # Step 2: Validate LiteMaaS Credentials
    # -------------------------------------------------------------------------
    - name: Test LiteMaaS API connection
      ansible.builtin.uri:
        url: "{{ litellm_api_base_url }}/models"
        method: GET
        headers:
          Authorization: "Bearer {{ litellm_virtual_key }}"
        validate_certs: false
        status_code: [200, 201]
      register: r_litemaas_check
      failed_when: false

    - name: Fail if LiteMaaS credentials invalid
      ansible.builtin.fail:
        msg: |
          LiteMaaS API credentials are invalid!
          Please check your API URL and virtual key.
          API URL: {{ litellm_api_base_url }}
      when: r_litemaas_check.failed | default(false)

    - name: Display LiteMaaS connection
      ansible.builtin.debug:
        msg: "✓ LiteMaaS API credentials valid"

    # -------------------------------------------------------------------------
    # Step 3: Install Collection
    # -------------------------------------------------------------------------
    - name: Install MaaS RAG Example collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install . --force
        chdir: "{{ playbook_dir }}"
      register: r_collection_install
      changed_when: "'Installing' in r_collection_install.stdout"

    - name: Display collection installation
      ansible.builtin.debug:
        msg: "✓ Collection installed"

    # -------------------------------------------------------------------------
    # Step 4: Deploy RAG Application
    # -------------------------------------------------------------------------
    - name: Deploy MaaS RAG workload
      ansible.builtin.include_role:
        name: maas_rag_example.maas_rag_example.ocp4_workload_maas_rag_example
      vars:
        ACTION: provision
        litellm_api_base_url: "{{ litellm_api_base_url }}"
        litellm_virtual_key: "{{ litellm_virtual_key }}"

    # -------------------------------------------------------------------------
    # Step 5: Wait for Build to Complete
    # -------------------------------------------------------------------------
    - name: Wait for build to complete
      kubernetes.core.k8s_info:
        api_version: build.openshift.io/v1
        kind: Build
        namespace: maas-rag-demo
      register: r_builds
      until:
        - r_builds.resources | length > 0
        - r_builds.resources | selectattr('status.phase', 'defined') | list | length > 0
        - r_builds.resources | map(attribute='status.phase') | select('in', ['Complete', 'Failed', 'Error', 'Cancelled']) | list | length > 0
      retries: 60
      delay: 10

    - name: Get latest build status
      ansible.builtin.set_fact:
        latest_build: "{{ r_builds.resources | sort(attribute='metadata.creationTimestamp') | last }}"

    - name: Fail if build failed
      ansible.builtin.fail:
        msg: |
          Build failed!
          Build name: {{ latest_build.metadata.name }}
          Phase: {{ latest_build.status.phase }}
          Check logs: oc logs -n maas-rag-demo build/{{ latest_build.metadata.name }}
      when: latest_build.status.phase in ['Failed', 'Error', 'Cancelled']

    - name: Display build success
      ansible.builtin.debug:
        msg: "✓ Build {{ latest_build.metadata.name }} completed successfully"

    # -------------------------------------------------------------------------
    # Step 6: Wait for Application Pod to be Ready
    # -------------------------------------------------------------------------
    - name: Wait for application pod to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: maas-rag-demo
        label_selectors:
          - app=maas-rag-app
      register: r_app_pods
      until:
        - r_app_pods.resources | length > 0
        - r_app_pods.resources | selectattr('status.conditions', 'defined') | list | length > 0
        - r_app_pods.resources | map(attribute='status.conditions') | select | map('selectattr', 'type', 'equalto', 'Ready') | list | length > 0
        - r_app_pods.resources | map(attribute='status.conditions') | select | map('selectattr', 'type', 'equalto', 'Ready') | map('selectattr', 'status', 'equalto', 'True') | list | length > 0
      retries: 30
      delay: 10

    - name: Display pod ready
      ansible.builtin.debug:
        msg: "✓ Application pod is ready"

    # -------------------------------------------------------------------------
    # Step 7: Display Access Information
    # -------------------------------------------------------------------------
    - name: Get application route
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        namespace: maas-rag-demo
        name: maas-rag-app
      register: r_final_route

    - name: Set final app URL
      ansible.builtin.set_fact:
        final_app_url: "https://{{ r_final_route.resources[0].spec.host }}"

    - name: Display deployment summary
      ansible.builtin.debug:
        msg:
          - ""
          - "========================================="
          - "🎉 MaaS RAG Example Deployed!"
          - "========================================="
          - ""
          - "Application URL: {{ final_app_url }}"
          - "Namespace: maas-rag-demo"
          - ""
          - "Test it now:"
          - "  export APP_URL='{{ final_app_url }}'"
          - ""
          - "  # Ingest a document"
          - "  curl -X POST $APP_URL/ingest \\"
          - "    -H 'Content-Type: application/json' \\"
          - "    -d '{\"title\": \"OpenShift\", \"content\": \"Red Hat OpenShift is a Kubernetes platform.\"}'"
          - ""
          - "  # Ask a question"
          - "  curl -X POST $APP_URL/ask \\"
          - "    -H 'Content-Type: application/json' \\"
          - "    -d '{\"question\": \"What is OpenShift?\"}'"
          - ""
          - "For detailed testing instructions, see INSTRUCTIONS.md"
          - ""
          - "========================================="
