---
# =============================================================================
# Ansible Collections Requirements
# =============================================================================
# Install these collections before running the deployment:
#   ansible-galaxy collection install -r requirements.yml
# =============================================================================

collections:
  # Kubernetes core modules for managing OpenShift resources
  - name: kubernetes.core
    version: ">=2.4.0"

  # This collection (maas_rag_example) - installed from current directory
  - name: .
    type: dir
