---
# =============================================================================
# Ansible Collections Requirements
# =============================================================================
# Install these collections before running the deployment:
#   ansible-galaxy collection install -r requirements.yml
# =============================================================================

collections:
  # Kubernetes core modules for managing OpenShift resources
  - name: kubernetes.core
    version: ">=2.4.0"

  # AgnosticD core for user_info module
  - name: agnosticd.core
    source: https://github.com/redhat-cop/agnosticd.git
    type: git
    version: development

  # This collection (install from local directory or GitHub)
  - name: maas_rag_example.maas_rag_example
    source: .
    type: dir
